package com.infinitepower.newquiz.domain.repository.multi_choice_quiz

import com.infinitepower.newquiz.model.multi_choice_quiz.MultiChoiceBaseCategory

interface FlagQuizRepository : MultiChoiceQuestionBaseRepository<MultiChoiceBaseCategory.Flag>
